name: Publish Helm Chart into GCR

on:
  workflow_call:
    secrets:
      google_credentials:
        required: true
    inputs:
      PROJECT_ID:
        description: 'A PROJECT ID input variable'
        type: string
        required: true
      IMAGE_NAME:
        description: 'A IMAGE NAME input variable'
        type: string
        required: true
      IMAGE_TAG:
        description: 'A IMAGE TAG input variable'
        type: string
        required: true
      deployment_file_path:
        description: 'The path to the deployment file'
        required: true
        type: string
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.google_credentials }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: mycluster1
          location: us-central1
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker for Google Container Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Update image version
        run: |
          echo "Image Tag is ${{ inputs.IMAGE_TAG }}"
          helm uninstall hello-world -n default
          helm install hello-world ./hello-world \
            --namespace default \
            --set image.tag=${{ inputs.IMAGE_TAG }} \
            --set image.name=${{ inputs.IMAGE_NAME }} \
            --set image.repository=gcr.io/${{ inputs.PROJECT_ID }}
      - name: Package Helm Chart
        run: |
          helm package hello-world
      - name: Push Helm Chart to Artifact Registry
        run: |
          helm push hello-world-*.tgz oci://us-central1-docker.pkg.dev/${{ inputs.PROJECT_ID }}/helm-charts-repo

      - name: Deploy Helm chart
        run: |
          echo "Image Tag is ${{ inputs.IMAGE_TAG }}"
          helm upgrade --install hello-world ./hello-world \
            --namespace default \
            --set image.repository=us-central1-docker.pkg.dev/${{ inputs.PROJECT_ID }}/helm-charts-repo \
            --set image.name=${{ inputs.IMAGE_NAME }} \
            --set image.tag=${{ inputs.IMAGE_TAG }}
